### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by jonathanhauge** [RainyDayMedia/techhub#48] opened 2015-10-01 14:42 UTC
"If I type “machining” in the processes search, I have no result but one supplier has mechanical machining in his category. It seems that you need to type exactly the same category name to have a result. I think it won’t show best results once fully deployed"

**Comment by Toddses** [comment] 2015-10-01 14:46
this is a duplicate of #49

**Closed by Toddses** 2015-10-01 14:46 UTC
Labels: duplicate
